In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
# creating own data set
df = pd.DataFrame({"x1":[3,2,1,-1,-5,-2,9,8,8],
                  "x2":[1,-4,1,-1,-5,-2,9,8,8],
                  "class":[1,1,-1,-1,-1,-1,1,1,-1]})
df

x1  x2  class
0   3   1      1
1   2  -4      1
2   1   1     -1
3  -1  -1     -1
4  -5  -5     -1
5  -2  -2     -1
6   9   9      1
7   8   8      1
8   8   8     -1

In [5]:
import numpy as np
w1 = int(input("Enter W1:"))
w2 = int(input("Enter W2:"))
eita = float(input("Enter learning rate:"))
bias = int(input("Enter bias:"))
w = [bias, w1, w2]

df1 = pd.DataFrame(columns = ['bias', 'w1', 'w2'])
i=0
for x in range (0, 9):
    row = [1]
    for y in range(0,2):
        row.append(df.iloc[x,y])
    row=np.array(row)
    out = np.dot(w, row)
    if out>=0:
        y1=1
    else :
        y1=-1
    d = df.iloc[x,2]
    w=w+eita*(d-y)*x
    print (w)
    df1.loc[i]=w
    i+=1
#df1.to_excel("output.xlsx")
df1

Enter W1:-4
Enter W2:-2
Enter learning rate:0.5
Enter bias:1
[ 1. -4. -2.]
[ 1. -4. -2.]
[-1. -6. -4.]
[-4. -9. -7.]
[ -8. -13. -11.]
[-13. -18. -16.]
[-13. -18. -16.]
[-13. -18. -16.]
[-21. -26. -24.]


bias    w1    w2
0   1.0  -4.0  -2.0
1   1.0  -4.0  -2.0
2  -1.0  -6.0  -4.0
3  -4.0  -9.0  -7.0
4  -8.0 -13.0 -11.0
5 -13.0 -18.0 -16.0
6 -13.0 -18.0 -16.0
7 -13.0 -18.0 -16.0
8 -21.0 -26.0 -24.0

# I tried :) 

In [ ]:
# lets not think about it right now
def take_input():


In [26]:
count = 0
def signum (x):
    return 1 if x>0 else -1

In [101]:

def linear_perceptron(input_val, weight, classs ):
    global count
    eita = 0.5
    input_val = np.array(input_val)
    weight = np.array(weight)
    y = signum(np.dot(input_val, weight))
    if y != classs :
        new_weight = weight + (eita*(classs - y))*input_val
        count+=1
        return linear_perceptron(input_val, new_weight, classs)
    else :
        print(f"Classified as :{y} and originally it was {classs}\nnumber of times weights were changed {count}\nnew updated weights are {weight}")
        

In [102]:

linear_perceptron([1,-4,-6], [-1,9,5], 1)
count =0 

Classified as :1 and originally it was 1
number of times weights were changed 2
new updated weights are [ 1.  1. -7.]
